// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPzSj7gblfR6lL1xsuRXOcxgcd_-Nqr9Y',
    appId: '1:794860272588:web:d850bea42943ae6fcabb69',
    messagingSenderId: '794860272588',
    projectId: 'tarot-a5e76',
    authDomain: 'tarot-a5e76.firebaseapp.com',
    storageBucket: 'tarot-a5e76.firebasestorage.app',
    measurementId: 'G-9SVSZL59MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtibt--mUIKJa2BDqrPBjwzWnqdwwaoGE',
    appId: '1:794860272588:android:3e95367b1c0f782ccabb69',
    messagingSenderId: '794860272588',
    projectId: 'tarot-a5e76',
    storageBucket: 'tarot-a5e76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcMRSIBGQlQP8AFUH3PfeouqJY7lzQ8Ek',
    appId: '1:794860272588:ios:de6777f1e3e8fe23cabb69',
    messagingSenderId: '794860272588',
    projectId: 'tarot-a5e76',
    storageBucket: 'tarot-a5e76.firebasestorage.app',
    iosBundleId: 'com.example.flutterTarot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcMRSIBGQlQP8AFUH3PfeouqJY7lzQ8Ek',
    appId: '1:794860272588:ios:de6777f1e3e8fe23cabb69',
    messagingSenderId: '794860272588',
    projectId: 'tarot-a5e76',
    storageBucket: 'tarot-a5e76.firebasestorage.app',
    iosBundleId: 'com.example.flutterTarot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPzSj7gblfR6lL1xsuRXOcxgcd_-Nqr9Y',
    appId: '1:794860272588:web:3ae70063d639d1edcabb69',
    messagingSenderId: '794860272588',
    projectId: 'tarot-a5e76',
    authDomain: 'tarot-a5e76.firebaseapp.com',
    storageBucket: 'tarot-a5e76.firebasestorage.app',
    measurementId: 'G-1VRSP7ER0S',
  );
}
